# Generated by Django 6.0.2 on 2026-02-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('semestre', models.IntegerField(default=1)),
                ('descricao', models.TextField()),
                ('dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Média'), ('D', 'Difícil'), ('P', 'Muito Difícil')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('empresa_ou_orgao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('link_inscricao', models.URLField(blank=True)),
                ('tipo', models.CharField(choices=[('E', 'Estágio'), ('B', 'Bolsa Acadêmica')], max_length=1)),
                ('data_postagem', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100)),
                ('definicao', models.TextField()),
            ],
        ),
    ]
