# Generated by Django 6.0.2 on 2026-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BolsaUFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nome da Bolsa')),
                ('orgao_emissor', models.CharField(max_length=100, verbose_name='Órgão (Ex: PROGRAD, PRAE, FEAAC)')),
                ('descricao', models.TextField(verbose_name='Requisitos e Benefícios')),
                ('link_edital', models.URLField(verbose_name='Link do Edital Oficial')),
                ('tipo', models.CharField(choices=[('MONITORIA', 'Monitoria'), ('PESQUISA', 'Iniciação Científica (PIBIC)'), ('EXTENSAO', 'Extensão'), ('APOIO', 'Auxílio Estudantil (PRAE)')], max_length=20)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bolsa UFC',
                'verbose_name_plural': 'Bolsas Acadêmicas UFC',
            },
        ),
        migrations.DeleteModel(
            name='Oportunidade',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='dificuldade',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='semestre',
        ),
    ]
