# Generated by Django 6.0.2 on 2026-02-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_bolsaufc_delete_oportunidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='dificuldade',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professores',
            field=models.CharField(default='A definir', help_text='´Professores que lecionam a cadeira', max_length=200, verbose_name='Professor(es) comum(ns)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre'), (3, '3º Semestre'), (4, '4º Semestre'), (5, '5º Semestre'), (6, '6º Semestre'), (7, '7º Semestre'), (8, '8º Semestre')], default=1),
        ),
    ]
