# Generated by Django 6.0.2 on 2026-02-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_remove_disciplina_professor_disciplina_dificuldade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkEssencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Sistema/Site')),
                ('descricao', models.CharField(max_length=200, verbose_name='Para que serve?')),
                ('url', models.URLField(verbose_name='Link de Acesso')),
                ('icone', models.CharField(default='fas fa-external-link-alt', help_text='Ícone FontAwesome (Ex: fas fa-laptop, fas fa-globe)', max_length=50)),
            ],
            options={
                'verbose_name': 'Link Essencial',
                'verbose_name_plural': 'Links Essenciais',
            },
        ),
        migrations.CreateModel(
            name='MaterialApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PROVA', 'Provas Antigas / Resoluções (Drive)'), ('PDF', 'Livro / Apostila / Resumo (PDF)'), ('VIDEO', 'Vídeo Aula (YouTube)'), ('PLANILHA', 'Planilha (Excel/Sheets)'), ('OUTRO', 'Outros Formatos')], max_length=20)),
                ('descricao', models.TextField(verbose_name='Resumo do Material')),
                ('link_acesso', models.URLField(verbose_name='Link do Arquivo (Google Drive, OneDrive, etc)')),
            ],
            options={
                'verbose_name': 'Material de Apoio',
                'verbose_name_plural': 'Materiais de Apoio',
            },
        ),
    ]
