# Generated by Django 6.0.2 on 2026-02-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_linkessencial_materialapoio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termofinanceiro',
            options={'ordering': ['termo']},
        ),
    ]
