# Generated by Django 6.0.2 on 2026-02-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_termofinanceiro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termofinanceiro',
            name='termo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
