# Generated by Django 6.0.2 on 2026-03-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_alter_termofinanceiro_termo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
